### ISSUE TITLE
[ Week 5 ]  5주차 워크북 미션

### ISSUE THREAD

**Issue by 20210699** [DS-UMC-7th/UMC-7th-Byam#1]
### 🛠 Mission

JPA 실습

### 📝 To-do

- [x] 테이블에 대한 Entity 생성
- [x] 연관관계 매핑 적용(양방향 매핑 포함)
- [x] 칼럼에 대한 세부 설정 적용

### 🔍 접근 방법

-
